### ISSUE TITLE
Error configure 32bit with debian stretch

### ISSUE THREAD

**Issue by mjnman** [mborjesson/PCem-wx-SDL2#2]
I tried to configure PCem with this options "./configure --build=i686-pc-linux-gnu "CFLAGS=-m32" "CXXFLAGS=-m32" "LDFLAGS=-m32"" but obtain error below:

checking for cpu... i686
checking for allegro-config... /usr/bin/allegro-config
checking for Allegro - version >= 4.0.0... no
*** Could not run Allegro test program, checking why...
*** The test program failed to compile or link. See the file config.log for the
*** exact error that occured. This usually means Allegro was incorrectly installed
*** or that you have moved Allegro since it was installed. In the latter case, you
*** may want to edit the allegro-config script: /usr/bin/allegro-config
configure: error: building PCem requires Allegro to be installed

on file config.log I can see:

configure:4166: result: i686
configure:4274: checking for allegro-config
configure:4292: found /usr/bin/allegro-config
configure:4305: result: /usr/bin/allegro-config
configure:4314: checking for Allegro - version >= 4.0.0
configure:4418: gcc -o conftest -O3 -I/usr/include  -m32 conftest.c -L/usr/lib/i386-linux-gnu -lalleg  >&5
//usr/lib/i386-linux-gnu/libXxf86vm.so.1: undefined reference to `_XEatDataWords'
collect2: error: ld returned 1 exit status
configure:4418: $? = 1
configure: program exited with status 1

I'm using Debian Stretch and I installed Allegro 4.0.0 i386

**Comment by mjnman** [comment]
I created a new VM in 32bit OS only.

**Comment by Marcellus-Wallace-Sr** [comment]
you have many clues.

1) check that //usr/lib/i386-linux-gnu/libXxf86vm.so.1: exists. follow
links if necessary

2) find out which module references AND defines `_XEatDataWords'.

3) make sure you don't have allegro 5 installed. (make sure EVERY file from
5 is not installed)

4) I have 4.2.2 installed and it works fine.

5) make sure:

export=LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64:${LD_LIBRARY_PATH}

**Comment by Marcellus-Wallace-Sr** [comment]
make sure you compiled allegro the 32 bit version only!!!!

**Comment by mjnman** [comment]
I prefer close the issue because it was a multipatch OS. I open a new issue with 32 bit OS version and new clear installation.
