### ISSUE TITLE
build error on 32bit Debian Stretch

### ISSUE THREAD

**Issue by mjnman** [mborjesson/PCem-wx-SDL2#3]
When build the source with "make" command on debian stretch 32bit obtain the errors bolow:

g++  -g -O2   -o pcem pcem-386.o pcem-386_dynarec.o pcem-386_dynarec_ops.o pcem-808x.o pcem-acer386sx.o pcem-ali1429.o pcem-amstrad.o pcem-cdrom-ioctl-linux.o pcem-cdrom-image.o pcem-cdrom-null.o pcem-codegen.o pcem-codegen_ops.o pcem-codegen_timing_486.o pcem-codegen_timing_686.o pcem-codegen_timing_pentium.o pcem-codegen_timing_winchip.o pcem-compaq.o pcem-config.o pcem-cpu.o pcem-dac.o pcem-dells200.o pcem-device.o pcem-disc.o pcem-disc_fdi.o pcem-disc_img.o pcem-disc_sector.o pcem-dma.o pcem-fdc.o pcem-fdc37c665.o pcem-fdd.o pcem-fdi2raw.o pcem-gameport.o pcem-hdd.o pcem-hdd_esdi.o pcem-headland.o pcem-i430lx.o pcem-i430fx.o pcem-i430vx.o pcem-ide.o pcem-intel.o pcem-intel_flash.o pcem-io.o pcem-jim.o pcem-joystick_ch_flightstick_pro.o pcem-joystick_standard.o pcem-joystick_sw_pad.o pcem-joystick_tm_fcs.o pcem-keyboard.o pcem-keyboard_amstrad.o pcem-keyboard_at.o pcem-keyboard_olim24.o pcem-keyboard_pcjr.o pcem-keyboard_xt.o pcem-laserxt.o pcem-lpt.o pcem-mca.o pcem-mcr.o pcem-mem.o pcem-mfm_at.o pcem-mfm_xebec.o pcem-model.o pcem-mouse.o pcem-mouse_ps2.o pcem-mouse_serial.o pcem-neat.o pcem-nmi.o pcem-nvr.o pcem-olivetti_m24.o pcem-opti495.o pcem-paths.o pcem-pc.o pcem-pci.o pcem-pic.o pcem-piix.o pcem-pit.o pcem-ppi.o pcem-ps1.o pcem-ps2.o pcem-ps2_mca.o pcem-ps2_nvr.o pcem-rom.o pcem-rtc.o pcem-scat.o pcem-serial.o pcem-sio.o pcem-sis496.o pcem-sound.o pcem-sound_ad1848.o pcem-sound_adlib.o pcem-sound_adlibgold.o pcem-sound_cms.o pcem-sound_emu8k.o pcem-sound_gus.o pcem-sound_mpu401_uart.o pcem-sound_opl.o pcem-sound_pas16.o pcem-sound_ps1.o pcem-sound_pssj.o pcem-sound_sb.o pcem-sound_sb_dsp.o pcem-sound_sn76489.o pcem-sound_speaker.o pcem-sound_ssi2001.o pcem-sound_wss.o pcem-sound_ym7128.o pcem-soundopenal.o pcem-tandy_eeprom.o pcem-tandy_rom.o pcem-timer.o pcem-um8669f.o pcem-um8881f.o pcem-vid_ati_eeprom.o pcem-vid_ati_mach64.o pcem-vid_ati18800.o pcem-vid_ati28800.o pcem-vid_ati68860_ramdac.o pcem-vid_cga.o pcem-vid_cl5429.o pcem-vid_colorplus.o pcem-vid_ega.o pcem-vid_et4000.o pcem-vid_et4000w32.o pcem-vid_genius.o pcem-vid_hercules.o pcem-vid_icd2061.o pcem-vid_ics2595.o pcem-vid_incolor.o pcem-vid_mda.o pcem-vid_olivetti_m24.o pcem-vid_oti067.o pcem-vid_paradise.o pcem-vid_pc200.o pcem-vid_pc1512.o pcem-vid_pc1640.o pcem-vid_pcjr.o pcem-vid_ps1_svga.o pcem-vid_s3.o pcem-vid_s3_virge.o pcem-vid_sdac_ramdac.o pcem-vid_stg_ramdac.o pcem-vid_svga.o pcem-vid_svga_render.o pcem-vid_tandy.o pcem-vid_tandysl.o pcem-vid_tgui9440.o pcem-vid_tkd8001_ramdac.o pcem-vid_tvga.o pcem-vid_unk_ramdac.o pcem-vid_vga.o pcem-vid_voodoo.o pcem-video.o pcem-wd76c10.o pcem-vid_wy700.o pcem-x86seg.o pcem-x87.o pcem-xtide.o pcem-sound_dbopl.o pcem-sound_resid.o pcem-cdrom_image.o pcem-dbopl.o pcem-vid_cga_comp.o pcem-convolve.o pcem-convolve-sse.o pcem-envelope.o pcem-extfilt.o pcem-filter.o pcem-pot.o pcem-sid.o pcem-voice.o pcem-wave6581_PS_.o pcem-wave6581_PST.o pcem-wave6581_P_T.o pcem-wave6581__ST.o pcem-wave8580_PS_.o pcem-wave8580_PST.o pcem-wave8580_P_T.o pcem-wave8580__ST.o pcem-wave.o  pcem-allegro-gui.o pcem-allegro-gui-config-sel.o pcem-allegro-gui-configure.o pcem-allegro-gui-deviceconfig.o pcem-allegro-gui-hdconf.o pcem-allegro-joystick.o pcem-allegro-keyboard.o pcem-allegro-main.o pcem-allegro-midi.o pcem-allegro-mouse.o pcem-allegro-video.o pcem-thread-pthread.o pcem-codegen_x86.o  -L/usr/lib/i386-linux-gnu -lalleg -lopenal -lpthread -lalut -lopenal 
pcem-sound_dbopl.o: In function `opl_init':
/home/dati/PCem-wx-SDL2-master/src/sound_dbopl.cc:50: undefined reference to `OPL3_Reset(opl3_chip*, unsigned int)'
pcem-sound_dbopl.o: In function `opl_write':
/home/dati/PCem-wx-SDL2-master/src/sound_dbopl.cc:96: undefined reference to `OPL3_WriteReg(opl3_chip*, unsigned short, unsigned char)'
/home/dati/PCem-wx-SDL2-master/src/sound_dbopl.cc:89: undefined reference to `OPL3_WriteAddr(opl3_chip*, unsigned int, unsigned char)'
pcem-sound_dbopl.o: In function `opl3_update':
/home/dati/PCem-wx-SDL2-master/src/sound_dbopl.cc:162: undefined reference to `OPL3_GenerateStream(opl3_chip*, short*, unsigned int)'
collect2: error: ld returned 1 exit status
Makefile:619: recipe for target 'pcem' failed
make[1]: *** [pcem] Error 1
make[1]: Leaving directory '/home/dati/PCem-wx-SDL2-master/src'
Makefile:368: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by Marcellus-Wallace-Sr** [comment]
That is the same error I'm getting.

**Comment by mborjesson** [comment]
Automake wasn't run on mainline for the latest merge. I've done so and committed the changes.
You can also run automake && autoconf and it should generate updated makefiles.

**Comment by mborjesson** [comment]
Also, if you wish to try out the new Linux GUI you can run configure with --enable-wx to enable it :)

**Comment by mjnman** [comment]
Thank you. Now compile work!

**Comment by mjnman** [comment]
The new GUI is very nice. I like it!
