### ISSUE TITLE
How to display the menu "Mainline"?

### ISSUE THREAD

**Issue by ThingUroboros** [mborjesson/PCem-wx-SDL2#6]
Hi i have a problem seeing this menu in the new version is hidden?

When I compile the new versions that I include before the menu and then give the load menu "Mainline" is not visible.

Does any keyboard shortcut go to view?

![pcem](https://user-images.githubusercontent.com/20670108/27984842-668d558e-63e0-11e7-892f-58f3beb3ecf7.png)

**Comment by mborjesson** [comment]
I changed it to right-click on the display-window to remove the dependency to have the machine-window open.

**Comment by ThingUroboros** [comment]
Thx :D
